### ISSUE TITLE
Navigation to nonexistent endpoint is allowed

### ISSUE THREAD

**Issue by scottaddie** [aspnet/HttpRepl#51]
If not taking advantage of tab completion, it's possible to navigate to an endpoint that doesn't exist. Consider the following web API containing `Fruits` and `People` endpoints.

```console
https://localhost:5001/~ ls
.        []
Fruits   [get|post]
People   [get|post]

https://localhost:5001/~ cd pe
/pe    []
```

When running `cd pe` in the preceding example, I would've expected:

* Navigation away from the web API root to be prevented.
* An error message such as "The pe endpoint doesn't exist".

/cc @tlmii

**Comment by tlmii** [comment]
I'm not sure what the proper expectation here is. 

When you don't have a swagger endpoint set (so the system doesn't know about the directory structure), you can still move around with the cd command to build up your proper URL to call. I think not limiting the user in that case makes sense since otherwise people without a swagger endpoint wouldn't be able to really use the tool.

But when we do know what the API structure is supposed to look like, should we limit the user? I'm not sure we should. There could be other endpoints outside of the swagger definition for whatever reason.

@jodavis any thoughts? @vijayrkn any historical context to that decision?

**Comment by jodavis** [comment]
@tlmii I definitely agree that in the case where you don't have a swagger endpoint set, we should not restrict the path. 

For consistency, I'm inclined to say we shouldn't be restrictive even when a swagger endpoint is set. Like you said, maybe there's some path that's not defined in swagger, and in that case I could see the user removing and re-adding the swagger definition to access the undocumented APIs.

But we might help the user by displaying a message as part of the command prompt. Something like

```
Warning: The 'pe' endpoint does not exist in the swagger definition
https://localhost:5001/~ |
```

(Replace any terminology that would be more consistent with the rest of the tool.)

That would call attention to a typo in the selected endpoint, but it could be ignored if the omitted endpoint was intentional.

**Comment by tlmii** [comment]
Now that #64 has been merged, I'll go ahead and close this.
